# Generated by Django 3.1.1 on 2020-09-21 10:31
import os

from django.contrib.postgres import operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    # If we're migrating pg12 specifically, change the order of the extensions
    # This should make is easier to have different OIDs on pg12 vs pg10
    operations = [
        operations.HStoreExtension(),
        operations.CITextExtension(),
    ][:: (-1 if os.environ.get("DJANGO_REVERSE_OPERATIONS", "0") == "1" else 1)]
