# Generated by Django 3.1.1 on 2020-09-21 10:31
from django.contrib.postgres import operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        operations.HStoreExtension(),
        operations.CITextExtension(),
    ]
